version: "2.4"
services:
  puppeth:
    image: ethereum/client-go:alltools-v1.9.10
    entrypoint: puppeth --network=whisper
    working_dir: /genesis/
    volumes:
      - ./genesis/:/genesis/

  bootnode:
    image: ethereum/client-go:alltools-v1.9.10
    entrypoint: bootnode
    command: "-nodekey /bootnode/bootnode.key -nat extip:172.31.2.1 -verbosity 6"
    volumes:
      - ./bootnode/:/bootnode/
    networks:
      whisper_net:
        ipv4_address: 172.31.2.1

  geth:
    image: ethereum/client-go:alltools-v1.9.10
    entrypoint: geth --datadir /datadir --keystore /keystore
    working_dir: /datadir/
    volumes:
      - ./datadir:/datadir/
      - ./keystore:/keystore/

  node1:
    image: ethereum/client-go:alltools-v1.9.10
    depends_on:
      - bootnode
      - ethstats
    entrypoint: geth --datadir /datadir --keystore /keystore --networkid 1337 --shh --rpc --rpcaddr '0.0.0.0' --rpcport 8545 --ws --wsaddr '0.0.0.0' --wsport 8546 -nat extip:172.31.2.2 --ethstats node1:nosecret@ethstats:3000 --bootnodes="enode://41d88842cd8d6e29d8baf237138bf6bf7a8b9689f82c2f0e6a96969e9f6aa239036877ce5dc2f6a724f2e64520f9d51b6e148a040b8fe6c836eea3ed10abb866@172.31.2.1:0?discport=30301"
    working_dir: /datadir/
    volumes:
      - ./datadir1:/datadir/
      - ./keystore:/keystore/
      - ./genesis/whisper.json:/genesis.json
    networks:
      whisper_net:
        ipv4_address: 172.31.2.2

  node2:
    image: ethereum/client-go:alltools-v1.9.10
    depends_on:
      - bootnode
      - ethstats
    entrypoint: geth --datadir /datadir --keystore /keystore --networkid 1337 --shh --rpc --rpcaddr '0.0.0.0' --rpcport 8545 --ws --wsaddr '0.0.0.0' --wsport 8546 -nat extip:172.31.2.3 --ethstats node2:nosecret@ethstats:3000 --bootnodes="enode://41d88842cd8d6e29d8baf237138bf6bf7a8b9689f82c2f0e6a96969e9f6aa239036877ce5dc2f6a724f2e64520f9d51b6e148a040b8fe6c836eea3ed10abb866@172.31.2.1:0?discport=30301"
    working_dir: /datadir/
    volumes:
      - ./datadir2:/datadir/
      - ./keystore:/keystore/
      - ./genesis/whisper.json:/genesis.json
    networks:
      whisper_net:
        ipv4_address: 172.31.2.3

  ethstats:
    image: puppeth/ethstats
    environment:
      - WS_SECRET=nosecret
    ports:
      - 3001:3000
    networks:
      whisper_net:

  app1:
    build: app1/
    depends_on:
      - node1
    networks:
      whisper_net:

  app2:
    build: app2/
    depends_on:
      - node2
    networks:
      whisper_net:

networks:
  whisper_net:
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16
